---
name: "Lint"

on:
  pull_request:
    paths:
      - "main.py"
      - "mdparser/**"
      - "poetry.lock"
      - "pyproject.toml"
      - ".github/workflows/lint.yml"
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

env:
  PY_COLORS: 1

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Prepare the job environment.
        uses: ./.github/workflows/prepare-action

      - name: Lint code.
        run: |
          poetry run isort --check --diff .
          poetry run black --check --diff .
